name: CI‑CD Docker local

on:
  push:
    branches: [ main, test ]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Définir le tag d’image
        id: vars
        run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Build & Push de l’image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/projetsmlops-3:${{ steps.vars.outputs.TAG }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Déploiement local avec docker-compose
        run: |
          cd /home/eleve/projetsmlops-3
          docker compose pull
          docker compose up -d

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mail.yahoo.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ✅ CI/CD terminé avec succès
          to: a_nyeck@yahoo.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Le workflow CI/CD dans le dépôt projetsmlops-3 s'est exécuté avec succès !
